# Generated by Django 6.0.8 on 2026-09-27 01:33

import bakery.services.costing
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('target_type', models.CharField(max_length=50, verbose_name='対象の種類')),
                ('target_id', models.BigIntegerField(null=True, verbose_name='対象の内部ID')),
                ('target_label', models.CharField(max_length=200, verbose_name='対象')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='変更前')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='変更後')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company')),
            ],
            options={
                'verbose_name': '変更履歴',
                'verbose_name_plural': '変更履歴',
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AllergenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=50, verbose_name='アレルゲン名')),
                ('kind', models.CharField(choices=[('mandatory', '義務'), ('recommended', '推奨')], max_length=15, verbose_name='区分')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('status', models.CharField(choices=[('active', '使用中'), ('stopped', '使用停止')], default='active', max_length=10, verbose_name='使用状態')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'アレルゲン項目',
                'verbose_name_plural': 'アレルゲン項目',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='IdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.company')),
            ],
            options={
                'verbose_name': '採番台帳',
                'verbose_name_plural': '採番台帳',
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(help_text='A、B … 食材IDの FOOD-A001 の A', max_length=5, verbose_name='分類コード')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー名')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('status', models.CharField(choices=[('active', '使用中'), ('stopped', '使用停止')], default='active', max_length=10, verbose_name='使用状態')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '食材カテゴリー',
                'verbose_name_plural': '食材カテゴリー',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(editable=False, max_length=20, verbose_name='食材ID')),
                ('name', models.CharField(max_length=100, verbose_name='食材名')),
                ('purchase_weight_g', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='購入重量（g）')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='購入価格（円）')),
                ('legacy_code', models.CharField(blank=True, max_length=30, verbose_name='旧コード')),
                ('additives', models.TextField(blank=True, verbose_name='添加物')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='原産国')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('active', '使用中'), ('stopped', '使用停止')], default='active', max_length=10, verbose_name='使用状態')),
                ('allergen_status', models.CharField(choices=[('unconfirmed', '未確認'), ('confirmed', '確認済み')], default='unconfirmed', max_length=15, verbose_name='アレルゲン確認')),
                ('allergen_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='アレルゲン確認日時')),
                ('allergen_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='アレルゲン確認者')),
                ('allergens', models.ManyToManyField(blank=True, related_name='ingredients', to='bakery.allergenitem', verbose_name='アレルゲン')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.ingredientcategory', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IngredientPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_weight_g', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='購入重量（g）')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='購入価格（円）')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='bakery.ingredient')),
            ],
            options={
                'verbose_name': '食材価格履歴',
                'verbose_name_plural': '食材価格履歴',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(editable=False, max_length=20, verbose_name='レシピID')),
                ('name', models.CharField(max_length=100, verbose_name='レシピ名')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='バージョン')),
                ('kind', models.CharField(choices=[('intermediate', '中間レシピ'), ('final', '最終商品レシピ')], max_length=15, verbose_name='区分')),
                ('recipe_type', models.CharField(blank=True, choices=[('dough', '生地'), ('filling', 'フィリング'), ('cream', 'クリーム'), ('sauce', 'ソース'), ('an', 'あん'), ('damande', 'ダマンド'), ('starter', '発酵種'), ('other', 'その他副材料')], max_length=15, verbose_name='種類')),
                ('yield_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='歩留まり')),
                ('preparation', models.TextField(blank=True, verbose_name='下処理')),
                ('procedure', models.TextField(blank=True, verbose_name='手順')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('status', models.CharField(choices=[('active', '使用中'), ('stopped', '使用停止')], default='active', max_length=10, verbose_name='使用状態')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company', verbose_name='会社')),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='bakery.recipe', verbose_name='コピー元')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'レシピ',
                'verbose_name_plural': 'レシピ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(editable=False, max_length=20, verbose_name='商品ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price_excluding_tax', models.PositiveIntegerField(verbose_name='税抜売価（円）')),
                ('status', models.CharField(choices=[('active', '使用中'), ('stopped', '使用停止')], default='active', max_length=10, verbose_name='使用状態')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('adopted_recipe', models.ForeignKey(blank=True, limit_choices_to={'kind': 'final'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adopted_by_products', to='bakery.recipe', verbose_name='採用レシピ')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='原価')),
                ('price_excluding_tax', models.PositiveIntegerField(verbose_name='税抜売価')),
                ('reason', models.CharField(choices=[('price_change', '食材価格変更'), ('adoption', '採用レシピ切替'), ('replacement', '中間レシピ置き換え')], max_length=20, verbose_name='原因')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('audit_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bakery.auditlog')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='bakery.product')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bakery.recipe')),
            ],
            options={
                'verbose_name': '原価記録',
                'verbose_name_plural': '原価記録',
                'ordering': ['-taken_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cost', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('new_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bakery.recipe')),
                ('old_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bakery.recipe')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='bakery.product')),
            ],
            options={
                'verbose_name': '採用レシピ切替履歴',
                'verbose_name_plural': '採用レシピ切替履歴',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='使用量（g）')),
                ('step_label', models.CharField(blank=True, max_length=50, verbose_name='工程')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_items', to='bakery.ingredient', verbose_name='食材')),
                ('material_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_items', to='bakery.recipe', verbose_name='中間レシピ')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bakery.recipe')),
            ],
            options={
                'verbose_name': 'レシピ明細',
                'verbose_name_plural': 'レシピ明細',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company')),
                ('new_recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bakery.recipe')),
                ('old_recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bakery.recipe')),
            ],
            options={
                'verbose_name': '中間レシピ置き換え履歴',
                'verbose_name_plural': '中間レシピ置き換え履歴',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('status', models.CharField(choices=[('active', '使用中'), ('stopped', '使用停止')], default='active', max_length=10, verbose_name='使用状態')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='bakery.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('general', '一般ユーザー'), ('admin', '管理者')], default='general', max_length=10, verbose_name='権限')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company', verbose_name='会社')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bakery.store', verbose_name='所属店舗')),
            ],
            options={
                'verbose_name': '所属・権限',
                'verbose_name_plural': '所属・権限',
            },
        ),
        migrations.CreateModel(
            name='StoreProductSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=True, verbose_name='販売する')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.store')),
            ],
            options={
                'verbose_name': '店舗販売設定',
                'verbose_name_plural': '店舗販売設定',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(editable=False, max_length=20, verbose_name='仕入先ID')),
                ('name', models.CharField(max_length=100, verbose_name='仕入先名')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='担当者')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='住所')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('active', '使用中'), ('stopped', '使用停止')], default='active', max_length=10, verbose_name='使用状態')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '仕入先',
                'verbose_name_plural': '仕入先',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bakery.supplier', verbose_name='仕入先'),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.08'), help_text='8% は 0.08', max_digits=5, verbose_name='税率')),
                ('unit_price_rounding', models.CharField(choices=[('none', '丸めない'), ('excel_roundup_2', '小数第2位へ切り上げ（既存Excelと同じ）')], default=bakery.services.costing.UnitPriceRounding['NONE'], max_length=20, verbose_name='1g単価の丸め')),
                ('default_yield_rate', models.DecimalField(decimal_places=4, default=Decimal('0.98'), max_digits=5, verbose_name='中間レシピの歩留まり')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='bakery.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'target_type', 'target_id'], name='bakery_audi_company_87101d_idx'),
        ),
        migrations.AddConstraint(
            model_name='allergenitem',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_allergen_name'),
        ),
        migrations.AddConstraint(
            model_name='idsequence',
            constraint=models.UniqueConstraint(fields=('company', 'prefix'), name='uniq_sequence_prefix'),
        ),
        migrations.AddConstraint(
            model_name='ingredientcategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_category_code'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_recipe_code'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'final'), ('recipe_type', '')), models.Q(('kind', 'intermediate'), models.Q(('recipe_type', ''), _negated=True)), _connector='OR'), name='recipe_type_only_for_intermediate'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('yield_rate__gt', 0), ('yield_rate__lte', 1)), name='recipe_yield_range'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_product_code'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('material_recipe__isnull', True)), models.Q(('ingredient__isnull', True), ('material_recipe__isnull', False)), _connector='OR'), name='recipe_item_exactly_one_material'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_g__gt', 0)), name='recipe_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='storeproductsetting',
            constraint=models.UniqueConstraint(fields=('store', 'product'), name='uniq_store_product'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_supplier_code'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_ingredient_code'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_weight_g__gte', 1)), name='ingredient_weight_min_1g'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='ingredient_price_not_negative'),
        ),
    ]
