# Generated by Django 6.0.8 on 2026-09-27 04:02

import bakery.services.costing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='cost_rounding',
            field=models.CharField(choices=[('ceil_1', '小数第1位へ切り上げ'), ('none', '丸めない')], default=bakery.services.costing.CostRounding['CEIL_1'], help_text='丸めた値を正式な商品原価とし、原価率・原価記録にも使う', max_length=20, verbose_name='商品原価の丸め'),
        ),
    ]
