# Generated by Django 6.0.8 on 2026-09-27 05:26

import bakery.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_recipe_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bakery.models.recipe_photo_path, verbose_name='写真')),
                ('thumbnail', models.ImageField(upload_to=bakery.models.recipe_photo_path, verbose_name='縮小画像')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='説明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='追加した人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bakery.product')),
            ],
            options={
                'verbose_name': '商品写真',
                'verbose_name_plural': '商品写真',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
