# Generated by Django 6.0.8 on 2026-09-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_number', models.CharField(max_length=10, unique=True, verbose_name='食品番号')),
                ('group', models.CharField(max_length=40, verbose_name='食品群')),
                ('name', models.CharField(max_length=200, verbose_name='食品名')),
                ('energy_kcal', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='エネルギー（kcal）')),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='たんぱく質（g）')),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='脂質（g）')),
                ('carbohydrate_g', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='炭水化物（g）')),
                ('salt_g', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='食塩相当量（g）')),
            ],
            options={
                'verbose_name': '食品成分表',
                'verbose_name_plural': '食品成分表',
                'ordering': ['food_number'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrate_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='炭水化物（g/100g）'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='energy_kcal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='熱量（kcal/100g）'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='脂質（g/100g）'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='栄養値の出どころ'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='たんぱく質（g/100g）'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='salt_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='食塩相当量（g/100g）'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bakery.foodcomposition', verbose_name='参照した成分表の食品'),
        ),
    ]
